# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170424_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.SmallIntegerField(),
        ),
    ]
