# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170424_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_posted',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='postedby', to='dashboard.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.User'),
        ),
    ]
