# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170425_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_posted',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='postedby', to='dashboard.User'),
        ),
    ]
