# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='related', to='friends.User'),
        ),
    ]
